translate documentation 06-legacy
Svelte-Society-Fr/svelte pull request #3
Opened 2023-07-04 15:54 UTC by Ennoriel

2023-07-05 06:21 UTC, iOiurson requested changes

2023-07-05 06:21 UTC, iOiurson commented on documentation/docs/06-legacy/01-svelte-register.md
> +> Cette méthode a été retirée à partir de Svelte 4. La méthode `require` a été dépréciée car les versions actuelles de Node comprennent directement le format ESM. Utilisez un <span class="vo">bundler
Je pense qu'on peut laisser `API` tel quel, je prépare un glossaire pour ce genre de termes. Peut-être mettre une classe `vo` du coup

2023-07-05 06:21 UTC, iOiurson commented on documentation/docs/06-legacy/01-svelte-register.md
> +> Cette méthode a été retirée à partir de Svelte 4. La méthode `require` a été dépréciée car les versions actuelles de Node comprennent directement le format ESM. Utilisez un <span class="vo">bundler
```suggestion
> Cette <span class="vo">API</span> a été retirée à partir de Svelte 4. La méthode `require` a été dépréciée car les versions actuelles de Node comprennent directement le format ESM. Utilisez un <span class="vo">bundler</span> comme Vite ou le <span class="vo">framework full-stack</span> [SvelteKit](https://kit.svelte.dev) à la place pour créer des modules Javascript à partir de composants Svelte.
```

2023-07-05 06:21 UTC, iOiurson commented on documentation/docs/06-legacy/01-svelte-register.md
> +Pour rendre des composants Svelte avec Node.js sans étape de compilation, utilisez `require('svelte/register')`.Vous pourrez alors utiliser la syntaxe `require` pour importe tout fichier ayant l'exte
"rendre" c'est un peu bizarre je trouve. "Faire un rendu" ?

2023-07-05 06:21 UTC, iOiurson commented on documentation/docs/06-legacy/01-svelte-register.md
> +> L'instruction `.default` est nécessaire car Svelte convertit à partir de modules Javascript natifs en modules CommonJS reconnus par Node. Notez que si vos composants importent des modules Javascrip
C'est pas vraiment une instruction il me semble. Je pense qu'on peut laisser "Le `.default`"
```suggestion
> Le `.default` est nécessaire car Svelte convertit à partir de modules Javascript natifs en modules CommonJS reconnus par Node. Notez que si vos composants importent des modules Javascript, ils n'arriveront pas à les charger dans un environnement Node et vous devrez utilisez un <span class="vo">bundler</span> à la place.
```

2023-07-05 06:21 UTC, iOiurson commented on documentation/docs/06-legacy/01-svelte-register.md
> +Pour passer des options de comiplation, ou pour utiliser des extensions de fichier personnalisés, appelez la méthode `register` comme une fonction :
```suggestion
Pour passer des options de compilation, ou pour utiliser des extensions de fichier personnalisées, appelez la méthode `register` comme une fonction :
```

2023-07-05 09:20 UTC, Ennoriel commented on documentation/docs/06-legacy/01-svelte-register.md
> +Pour rendre des composants Svelte avec Node.js sans étape de compilation, utilisez `require('svelte/register')`.Vous pourrez alors utiliser la syntaxe `require` pour importe tout fichier ayant l'exte
```suggestion
Pour faire un rendu des composants Svelte avec Node.js sans étape de compilation, utilisez `require('svelte/register')`.Vous pourrez alors utiliser la syntaxe `require` pour importe tout fichier ayant l'extension `.svelte`.
```

2023-07-05 09:21 UTC, Ennoriel commented
normalement, tout est revu

2023-07-07 06:41 UTC, iOiurson commented on sites/svelte.dev/src/routes/+layout.svelte
> -		color: white;
Je ne suis pas sur d'être d'accord avec ces changements de style. Je trouvais ça bien de mettre en valeur (via du blanc) le survol du lien

2023-07-07 06:44 UTC, iOiurson commented on sites/svelte.dev/src/routes/+layout.svelte
> -		color: white;
Ah je vois le problème, en mode light tout est blanc... Ça serait bien qu'en light en utilise du noir plutôt.

Je valide cette MR, je regarderai ce détail plus tard.

2023-07-07 06:44 UTC, iOiurson approved these changes

2023-07-07 06:44 UTC, merged