WIP: translate documentation 05-misc
Svelte-Society-Fr/svelte pull request #4
Opened 2023-07-04 16:34 UTC by Ennoriel

J'ai retraduit quelques sections de l'accessibilité. Il reste la nouvelle partie typescript et migration v4

2023-07-07 07:23 UTC, iOiurson requested changes

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/01-faq.md
> +**Tests <span class="vo">[end to end](/docs/development#end-to-end)</span>** : Pour vous assurer que votre application fonctionne comme prévu dans des cas réels d'utilisation, il est nécessaire de la
```suggestion
_Tests <span class="vo">[end to end](/docs/development#end-to-end)</span>_ : Pour vous assurer que votre application fonctionne comme prévu dans des cas réels d'utilisation, il est nécessaire de la tester d'une manière la plus proche possible de la production. Cela se fait avec des tests dits <span class="vo">[end to end](/docs/development#end-to-end)</span> (E2E) qui chargent et interagissent avec une version déployée de votre application afin de simuler les interactions utilisateur. Lorsque vous créez un nouveau projet SvelteKit, vous avez la possibilité de choisir d'installer [Playwright](https://playwright.dev/) pour les tests <span class="vo">[end to end](/docs/development#end-to-end)</span>. Il existe également d'autres librairies de tests E2E.
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/01-faq.md
> +La bibliothèque officielle de routage est [SvelteKit](https://kit.svelte.dev/). Sveltekit fournit un routeur basé sur le système de fichier, un rendu coté serveur (SSR) et un rechargement automatique
Je pense que je préfère utiliser "routing" plutôt que "routage" et rajouter une entrée au glossaire.

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/01-faq.md
> +[Routify](https://routify.dev) est un autre router basé sur l'arborescence de fichiers, similaire au router de SvelteKit. La version 3 supporte le rendu côté serveur natif de Svelte.
```suggestion
[Routify](https://routify.dev) est un autre routeur basé sur l'arborescence de fichiers, similaire au routeur de SvelteKit. La version 3 supporte le rendu côté serveur natif de Svelte.
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/01-faq.md
> +Vous pouvez trouver une [liste de routers maintenus par la communauté sur sveltesociety.dev](https://sveltesociety.dev/components#routers).
```suggestion
Vous pouvez trouver une [liste de routeurs maintenus par la communauté sur sveltesociety.dev](https://sveltesociety.dev/components#routers).
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/01-faq.md
> +Nous vous recommandons d'utiliser [SvelteKit](https://kit.svelte.dev/), qui prend en charge le rechargement automatique (HMR) prêt à l'emploi et est construit avec [Vite](https://vitejs.dev/) et [sve
Ajouter un lien pour "plugin"

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Certains éléments DOM spéciaux ne prennent pas en charge les rôles, états et propriétés ARIA. C'est souvent parce qu'ils ne sont pas visibles, comme `meta`, `html`, `script`, `style`. Cette règle gar
Lien pour DOM, et ARIA

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Certains éléments DOM sont utiles pour la navigation avec lecteur d'écran et ne doivent pas être cachés.
Lien pour DOM

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Assure que les éléments avec un rôle interactif et des gestionnaires d'évènements interactifs (de souris ou de clavier) soient focalisables ou accessibles avec la touche Tab.
Tu as mis `la touche "Tabulation"` plus haut, ça serait bien de mettre pareil dans les 2 (j'ai une préférence pour Tab)

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Certains éléments DOM réservés ne prennent pas en charge les rôles, états et propriétés ARIA. Cela est souvent dû à leur invisibilité, par exemple `meta`, `html`, `script`, `style`. Cette règle impos
Lien pour DOM et ARIA

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +- `<a>` devrait avoir un href (sauf s'il s'agit d'une [balise définissant un fragment](https://github.com/sveltejs/svelte/issues/4697))
```suggestion
- `<a>` devrait avoir un `href` (sauf s'il s'agit d'une [balise définissant un fragment](https://github.com/sveltejs/svelte/issues/4697))
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +- `<area>` devrait avoir alt, aria-label ou aria-labelledby
```suggestion
- `<area>` devrait avoir `alt`, `aria-label` ou `aria-labelledby`
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +- `<html>` devrait avoir lang
```suggestion
- `<html>` devrait avoir `lang`
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +- `<iframe>` devrait avoir title
```suggestion
- `<iframe>` devrait avoir `title`
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +- `<img>` devrait avoir alt
```suggestion
- `<img>` devrait avoir `alt`
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +- `<object>` devrait avoir title, aria-label ou aria-labelledby
```suggestion
- `<object>` devrait avoir `title`, `aria-label` ou `aria-labelledby`
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +- `<input type="image">` devrait avoir alt, aria-label ou aria-labelledby
```suggestion
- `<input type="image">` devrait avoir `alt`, `aria-label` ou `aria-labelledby`
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Certains éléments HTML ont des rôles ARIA par défaut. Donner à ces éléments un rôle ARIA déjà défini par le navigateur [n'a aucun effet](https://www.w3.org/TR/using-aria/#aria-does-nothing) et est re
Lien pour ARIA

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Les rôles [WAI-ARIA](https://www.w3.org/TR/wai-aria-1.1/#usage_intro) ne devraient pas être utilisés pour convertir un élément interactif en un élément non interactif. Les rôles ARIA non interactifs
Lien pour ARIA

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Les éléments comme un `<div>` avec des gestionnaires d'événements comme `click` doivent avoir un rôle ARIA.
Lien pour ARIA

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Les éléments avec des rôles ARIA doivent avoir tous les attributs requis pour ce rôle.
Lien pour ARIA

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Assure que certains éléments DOM aient la bonne structure.
Lien pour DOM

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Assure que seuls les attributs ARIA connus soient utilisés. Cela est basé sur la spécification [WAI-ARIA States and Properties](https://www.w3.org/WAI/PF/aria-1.1/states_and_properties).
Lien pour ARIA

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/02-accessibility-warnings.md
> +Les éléments avec des rôles ARIA doivent utiliser un rôle ARIA valide et non abstrait. Une référence aux définitions de rôle peut être trouvée sur le site [WAI-ARIA](https://www.w3.org/TR/wai-aria/#r
Lien pour ARIA

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/03-typescript.md
> +Vous pouvez utiliser TypeScript dans vos composants. Des extensions d'<span class="vo">[IDE](/docs/development#ide)</span> comme l'[extension Svelte VSCode](https://marketplace.visualstudio.com/items
```suggestion
Vous pouvez utiliser TypeScript dans vos composants. Des extensions d'<span class="vo">[IDE](/docs/development#ide)</span> comme l'[extension Svelte VSCode](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) vous aideront à voir et corriger les erreurs directement dans votre éditeur, et [`svelte-check`](https://www.npmjs.com/package/svelte-check) fera la même chose en ligne de commande, que vous pouvez ajouter à votre chaîne d'intégration continue.
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/03-typescript.md
> +Les slots et les types de leurs props sont déduits des types des props qui leurs sont passées :
Liens pour Slots et props

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/03-typescript.md
> +Svelte fournit des types aussi proche que possible pour chaque élément HTML du <span class="vo">[DOM](/docs/web#dom)</span> qui existe. Parfois, vous voudrez utiliser des attributs expérimentaux ou d
Lien pour PR et issue

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/03-typescript.md
> +Svelte fournit des types aussi proche que possible pour chaque élément HTML du <span class="vo">[DOM](/docs/web#dom)</span> qui existe. Parfois, vous voudrez utiliser des attributs expérimentaux ou d
```suggestion
Svelte fournit des types aussi proches que possible pour chaque élément HTML du <span class="vo">[DOM](/docs/web#dom)</span> qui existe. Parfois, vous voudrez utiliser des attributs expérimentaux ou des événements personnalisés. Dans ces cas, TypeScript lèvera une erreur de type, en indiquant qu'il ne connaît pas ces types. S'il s'agit d'un attribut ou événement standard et non expérimental, il se peut tout à fait que ce soit un type manquant dans [le typage HTML de Svelte](https://github.com/sveltejs/svelte/blob/master/elements/index.d.ts). Dans ce cas, vous êtes le bienvenu pour ouvrir une issue ou une PR pour le corriger.
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/03-typescript.md
> +Quelques fonctionnalités sont manquantes pour bénéficier de tous les avantages de TypeScript dans des cas plus avancés, comme pour typer qu'un composant étend une interface, pour typer les slots ou p
Lien pour slot

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +Si vous êtes l'auteur d'une librairie, considérez bien le choix de ne supporter que Svelte 4 ou, si cela est possible, de continuer à supporter Svelte 3 également. Comme la plupart des changements no
```suggestion
Si vous êtes l'auteur d'une librairie, considérez bien le choix de ne supporter que Svelte 4 ou, si cela est possible, de continuer à supporter Svelte 3 également. Comme la plupart des changements non réversibles n'affectent que peu de personnes, cela est facilement faisable la plupart du temps. Enfin, n'oubliez pas de mettre à jour la plage de versions des `peerDependencies`.
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +- Mettre à jours vers Node 16 ou plus. Les versions précédentes ne sont plus supportées. ([#8566](https://github.com/sveltejs/svelte/issues/8566))
```suggestion
- Mettre à jour vers Node 16 ou plus. Les versions précédentes ne sont plus supportées. ([#8566](https://github.com/sveltejs/svelte/issues/8566))
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +- Si vous utilisez webpack, mettez sa version à 5 ou plus et `svelte-loader` à 3.1.8 ou plus. Les versions précédente ne sont plus supportées. ([#8515](https://github.com/sveltejs/svelte/issues/8515)
```suggestion
- Si vous utilisez webpack, mettez sa version à 5 ou plus et `svelte-loader` à 3.1.8 ou plus. Les versions précédentes ne sont plus supportées. ([#8515](https://github.com/sveltejs/svelte/issues/8515), [198dbcf](https://github.com/sveltejs/svelte/commit/198dbcf))
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +- Si vous utilisez TypeScript, mettez sa version à 5.0.0 ou plus. Les versions précédentes pourront probablement toujours fonctionner, mais aucune garantie n'est fait pour autant. ([#8488](https://gi
```suggestion
- Si vous utilisez TypeScript, mettez sa version à 5.0.0 ou plus. Les versions précédentes pourront probablement toujours fonctionner, mais nous ne pouvons pas le garantir. ([#8488](https://github.com/sveltejs/svelte/issues/8488))
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +Svelte ne supporte plus le format CommonJS (CJS) comme format de sortie de la compilation. L'API `svelte/register` a été retiré ainsi que la version de runtime CJS. Si vous avez besoin de garder le f
Lien pour API

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +Svelte ne supporte plus le format CommonJS (CJS) comme format de sortie de la compilation. L'API `svelte/register` a été retiré ainsi que la version de runtime CJS. Si vous avez besoin de garder le f
```suggestion
Svelte ne supporte plus le format CommonJS (CJS) comme format de sortie de la compilation. L'API `svelte/register` a été retirée ainsi que la version de runtime CJS. Si vous avez besoin de garder le format de sortie CJS, utilisez un <span class="vo">[bundler](/docs/web#bundler)</span> pour convertir la sortie ESM en CJS avec une étape de post-build. ([#8613](https://github.com/sveltejs/svelte/issues/8613))
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +## Typage plus Strict pour les fonctions Svelte
```suggestion
## Typage plus strict pour les fonctions Svelte
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +- `Action` et `ActionReturn` ont maintenant un type d'argument par défault à `undefined`, ce qui signifie que vous devez typez le <span class="vo">[generic](/docs/javascript#generic)</span> si vous v
```suggestion
- `Action` et `ActionReturn` ont maintenant un type d'argument par défault à `undefined`, ce qui signifie que vous devez typer le <span class="vo">[generic](/docs/javascript#generic)</span> si vous voulez spécifier que cette action reçoit un paramètre. Le script de migration prendra cette règle en compte automatiquement ([#7442](https://github.com/sveltejs/svelte/pull/7442))
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +La création des <span class="vo">[Custom Elements](/docs/development#custom-elements)</span> avec Svelte a complètement été refondu et significativement amélioré. L'option `tag` a été déprécié en fav
```suggestion
La création des <span class="vo">[Custom Elements](/docs/development#custom-elements)</span> avec Svelte a complètement été repensée et significativement améliorée. L'option `tag` a été dépréciée en faveur de la nouvelle option `customElement` :
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +Ce changement est intervenu pour permettre [une configuration plus importante](custom-elements-api#component-options) pour des cas d'usages avancés. Le code de migration ajustera votre code automatiq
```suggestion
Ce changement est intervenu pour permettre [une meilleure configuration](custom-elements-api#component-options) pour des cas d'usages avancés. Le code de migration ajustera votre code automatiquement. La temporalité des changements des propriétés a également légèrement changée. ([#8457](https://github.com/sveltejs/svelte/issues/8457))
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +`SvelteComponentTyped` est déprécié, car `SvelteComponent` comporte tous le typage nécessaire. Remplacez toutes les instances de `SvelteComponentTyped` par `SvelteComponent`.
```suggestion
`SvelteComponentTyped` est déprécié, car `SvelteComponent` contient tout le typage nécessaire. Remplacez toutes les instances de `SvelteComponentTyped` par `SvelteComponent`.
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +Si vous utilisiez `SvelteComponent` comme type d'instance de composant précédemment, vous pourriez maintenant voir une erreur de type étrange, qui est résolue en changeant ` : typeof SvelteComponent`
```suggestion
Si par le passé vous utilisiez `SvelteComponent` comme type d'instance de composant, vous pourriez maintenant voir une erreur de type étrange, qui est résolue en changeant ` : typeof SvelteComponent` par ` : typeof SvelteComponent<any>`.
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +Les liaisons de slots par défaut ne sont plus exposées aux slots nommés et vice versa :
Lien pour slot

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +Cela rend les liaisons de slots plus cohérentes car le comportement est indéfini lorsque, par exemple, le slot par défaut provient d'une liste et que le slot nommé n'en fait pas partie. ([#6049](http
Lien pour slot

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +## nouvelle librairie eslint
```suggestion
## Nouvelle librairie eslint
```

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +- `derived` lancera maintenant une erreur sur les valeurs falsy au lieu des stores qui lui sont passés. ([#7947](https://github.com/sveltejs/svelte/issues/7947))
Lien pour falsy et stores

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +- le runtime utilise maintenant le constructeur `CustomEvent` qui peut ne pas fonctionner dans les très vieux navigateurs. Envisagez d'utiliser un [polyfill] (https://github.com/theftprevention/event
Lien pour runtime

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +- les définitions de type pour `svelte/internal` ont été supprimées pour décourager encore plus l'utilisation de ces méthodes internes qui ne sont pas des API publiques. La plupart de ces éléments se
Lien pour API

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +- La suppression des noeuds du DOM se fait maintenant par lots, ce qui modifie légèrement l'ordre, ce qui peut affecter l'ordre des événements déclenchés si vous utilisez un `MutationObserver` sur ce
Lien pour DOM

2023-07-07 07:23 UTC, iOiurson commented on documentation/docs/05-misc/04-v4-migration-guide.md
> +- si vous avez étendu les typages globaux à travers l'espace de nom `svelte.JSX` auparavant, vous devez les migrer pour utiliser l'espace de nom `svelteHTML`. De même, si vous avez utilisé l'espace d
"espace de nom" => namespace + lien

2023-07-07 07:28 UTC, iOiurson requested changes
Rah, je crois que j'ai perdu plein de commentaires... faudra que je recheck

Edit: ah non, je crois que c bon en fait, il y a bien mes commentaires

2023-07-12 18:49 UTC, Ennoriel commented on documentation/docs/05-misc/01-faq.md
> -$: x = count + 1;
?

2023-07-12 18:49 UTC, Ennoriel commented on documentation/docs/05-misc/01-faq.md
> +La bibliothèque officielle de routage est [SvelteKit](https://kit.svelte.dev/). Sveltekit fournit un routeur basé sur le système de fichier, un rendu coté serveur (SSR) et un rechargement automatique
```suggestion
La bibliothèque officielle de <span class="vo">[routing](/docs/web#route)</span> est [SvelteKit](https://kit.svelte.dev/). Sveltekit fournit un routeur basé sur le système de fichier, un rendu coté serveur (SSR) et un rechargement automatique de module (HMR) en une seule librairie facile à utiliser. Il est similaire à Next.js pour React.
```

2023-07-26 11:56 UTC, closed without merging